ibm_dbt:
  outputs:
    dev:
      account: JUDRYDG-OX54644
      database: TRANSFORMED_DEV
      authenticator: SNOWFLAKE_JWT
      private_key_path: /Users/vitorduarte/snowflake_dbt/rsa_key.p8
      role: ROLE_DBT_USER_DEV
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: DBT_USER
      warehouse: WH_DBT_USER_DEV
  target: dev
