USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS ADMIN_DB;
CREATE SCHEMA IF NOT EXISTS ADMIN_DB.NETWORK WITH MANAGED ACCESS;

CREATE AUTHENTICATION POLICY ADMIN_DB.NETWORK.TRAINING_SERVICE_ACCOUNT
  PAT_POLICY=(
    NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED
  );

ALTER USER <YOUR USERNAME> SET AUTHENTICATION POLICY ADMIN_DB.NETWORK.TRAINING_SERVICE_ACCOUNT;

-- ALTER USER DBT_USER SET AUTHENTICATION POLICY ADMIN_DB.NETWORK.TRAINING_SERVICE_ACCOUNT;

-- ALTER USER DATA_INGEST_USER SET AUTHENTICATION POLICY ADMIN_DB.NETWORK.TRAINING_SERVICE_ACCOUNT;
