-- ==========================================================
-- Snowflake RBAC + Infra Bootstrap for ELT/dbt Project
-- Envs: DEV, PROD
-- Databases: RAW_<ENV>, TRANSFORMED_<ENV>
-- Raw schemas: SOURCE1, SOURCE2
-- ==========================================================

-- Run as SECURITYADMIN / ACCOUNTADMIN as appropriate
USE ROLE ACCOUNTADMIN;

-- ==========================================================
-- 1) CREATE ROLES
-- ==========================================================

-- Ownership roles (single owner strategy)
-- Each database has its own owner
CREATE ROLE IF NOT EXISTS ROLE_OWNER_RAW_DEV;
CREATE ROLE IF NOT EXISTS ROLE_OWNER_RAW_PROD;
CREATE ROLE IF NOT EXISTS ROLE_OWNER_TRANSFORMED_DEV;
CREATE ROLE IF NOT EXISTS ROLE_OWNER_TRANSFORMED_PROD;

-- Schema Creator
CREATE ROLE IF NOT EXISTS ROLE_SCHEMA_CREATE_RAW_DEV;
CREATE ROLE IF NOT EXISTS ROLE_SCHEMA_CREATE_RAW_PROD;
CREATE ROLE IF NOT EXISTS ROLE_SCHEMA_CREATE_TRANSFORMED_DEV;
CREATE ROLE IF NOT EXISTS ROLE_SCHEMA_CREATE_TRANSFORMED_PROD;

-- Access roles - DEV
-- Split by database
CREATE ROLE IF NOT EXISTS ROLE_RAW_DEV_READ;
CREATE ROLE IF NOT EXISTS ROLE_RAW_DEV_WRITE;
CREATE ROLE IF NOT EXISTS ROLE_RAW_DEV_CREATE;

CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_DEV_READ;
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_DEV_WRITE;
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_DEV_CREATE;

-- Access roles - PROD
CREATE ROLE IF NOT EXISTS ROLE_RAW_PROD_READ;
CREATE ROLE IF NOT EXISTS ROLE_RAW_PROD_WRITE;
CREATE ROLE IF NOT EXISTS ROLE_RAW_PROD_CREATE;

CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_PROD_READ;
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_PROD_WRITE;
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMED_PROD_CREATE;

-- Functional roles - DEV
CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER_DEV;
CREATE ROLE IF NOT EXISTS ROLE_DATA_INGEST_DEV;
CREATE ROLE IF NOT EXISTS ROLE_DBT_USER_DEV;
CREATE ROLE IF NOT EXISTS ROLE_DBT_SERVICE_ACCOUNT_DEV;

-- Functional roles - PROD
CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER_PROD;
CREATE ROLE IF NOT EXISTS ROLE_DATA_INGEST_PROD;
CREATE ROLE IF NOT EXISTS ROLE_DBT_USER_PROD;
CREATE ROLE IF NOT EXISTS ROLE_DBT_SERVICE_ACCOUNT_PROD;

-- Optional: cross-env reader for engineers
CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER_ALL_READ;
