-- ==========================================================
-- 1) CREATE DATABASES + RAW SCHEMAS USING OWNER ROLES
-- ==========================================================

-- RAW DEV
CREATE DATABASE IF NOT EXISTS RAW_DEV;
GRANT OWNERSHIP ON DATABASE RAW_DEV TO ROLE ROLE_OWNER_RAW_DEV;
-- Ingest activities can create schemas

-- RAW PROD
CREATE DATABASE IF NOT EXISTS RAW_PROD;
GRANT OWNERSHIP ON DATABASE RAW_PROD TO ROLE ROLE_OWNER_RAW_PROD;
-- Ingest activities can create schemas


-- TRANSFORMED DEV
CREATE DATABASE IF NOT EXISTS TRANSFORMED_DEV;
GRANT OWNERSHIP ON DATABASE TRANSFORMED_DEV TO ROLE ROLE_OWNER_TRANSFORMED_DEV;
-- dbt will create schemas here

-- TRANSFORMED PROD
CREATE DATABASE IF NOT EXISTS TRANSFORMED_PROD;
GRANT OWNERSHIP ON DATABASE TRANSFORMED_PROD TO ROLE ROLE_OWNER_TRANSFORMED_PROD;
-- dbt will create schemas here
