-- Example "service account" user
CREATE USER IF NOT EXISTS DBT_USER
    LOGIN_NAME = 'DBT_USER'
    DISPLAY_NAME = 'dbt service account'
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ROLE_DBT_USER_DEV TO USER DBT_USER;
GRANT ROLE ROLE_DBT_USER_PROD TO USER DBT_USER;
ALTER USER DBT_USER SET DEFAULT_ROLE = ROLE_DBT_USER_DEV, DEFAULT_WAREHOUSE = WH_DBT_USER_DEV;

CREATE USER IF NOT EXISTS DATA_INGEST_USER
    LOGIN_NAME = 'DATA_INGEST_USER'
    DISPLAY_NAME = 'Data Ingest User'
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ROLE_DATA_INGEST_DEV  TO USER DATA_INGEST_USER;
GRANT ROLE ROLE_DATA_INGEST_PROD TO USER DATA_INGEST_USER;
ALTER USER DATA_INGEST_USER SET DEFAULT_ROLE = ROLE_DATA_INGEST_DEV, DEFAULT_WAREHOUSE = WH_DATA_INGEST_DEV;
