-- ==========================================================
-- 1) GRANT WAREHOUSE USAGE TO FUNCTIONAL ROLES
-- ==========================================================

-- DEV
GRANT USAGE, OPERATE ON WAREHOUSE WH_DATA_ENGINEER_DEV TO ROLE ROLE_DATA_ENGINEER_DEV;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DATA_INGEST_DEV   TO ROLE ROLE_DATA_INGEST_DEV;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DBT_USER_DEV      TO ROLE ROLE_DBT_USER_DEV;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DBT_SVC_DEV       TO ROLE ROLE_DBT_SERVICE_ACCOUNT_DEV;

-- PROD
GRANT USAGE, OPERATE ON WAREHOUSE WH_DATA_ENGINEER_PROD TO ROLE ROLE_DATA_ENGINEER_PROD;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DATA_INGEST_PROD   TO ROLE ROLE_DATA_INGEST_PROD;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DBT_USER_PROD      TO ROLE ROLE_DBT_USER_PROD;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DBT_SVC_PROD       TO ROLE ROLE_DBT_SERVICE_ACCOUNT_PROD;

-- ==========================================================
-- 2) GRANT CREATE SCHEMAS
-- ==========================================================
--
-- ----- SCHEMAS -----
GRANT CREATE SCHEMA ON DATABASE RAW_DEV          TO ROLE ROLE_SCHEMA_CREATE_RAW_DEV;
GRANT CREATE SCHEMA ON DATABASE RAW_PROD         TO ROLE ROLE_SCHEMA_CREATE_RAW_PROD;
GRANT CREATE SCHEMA ON DATABASE TRANSFORMED_DEV  TO ROLE ROLE_SCHEMA_CREATE_TRANSFORMED_DEV;
GRANT CREATE SCHEMA ON DATABASE TRANSFORMED_PROD TO ROLE ROLE_SCHEMA_CREATE_TRANSFORMED_PROD;


-- ==========================================================
-- 3) RAW ACCESS GRANTS
-- ==========================================================
--
-- ----- DEV RAW -----
GRANT USAGE ON DATABASE RAW_DEV                   TO ROLE ROLE_RAW_DEV_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV    TO ROLE ROLE_RAW_DEV_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_READ;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DEV    TO ROLE ROLE_RAW_DEV_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_DEV     TO ROLE ROLE_RAW_DEV_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_DEV  TO ROLE ROLE_RAW_DEV_READ;

GRANT USAGE ON DATABASE RAW_DEV                                             TO ROLE ROLE_RAW_DEV_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV                              TO ROLE ROLE_RAW_DEV_WRITE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DEV                           TO ROLE ROLE_RAW_DEV_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE RAW_DEV    TO ROLE ROLE_RAW_DEV_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_WRITE;

GRANT USAGE ON DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK,
CREATE DCM PROJECT, CREATE DBT PROJECT, CREATE PROCEDURE, CREATE FUNCTION
  ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK,
CREATE DCM PROJECT, CREATE DBT PROJECT, CREATE PROCEDURE, CREATE FUNCTION
  ON FUTURE SCHEMAS IN DATABASE RAW_DEV TO ROLE ROLE_RAW_DEV_CREATE;

-- ----- PROD RAW -----
GRANT USAGE ON DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_READ;

GRANT USAGE ON DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_WRITE;

GRANT USAGE ON DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK,
CREATE DCM PROJECT, CREATE DBT PROJECT, CREATE PROCEDURE, CREATE FUNCTION
  ON ALL SCHEMAS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK,
CREATE DCM PROJECT, CREATE DBT PROJECT, CREATE PROCEDURE, CREATE FUNCTION
  ON FUTURE SCHEMAS IN DATABASE RAW_PROD TO ROLE ROLE_RAW_PROD_CREATE;

-- ==========================================================
-- 4) TRANSFORMED ACCESS GRANTS
-- ==========================================================

-- ----- DEV TRANSFORMED -----
-- <TO BE FILLED IN THE TRAINING>


-- ==========================================================
-- 5) ROLE HIERARCHY (ACCESS ROLES -> FUNCTIONAL ROLES)
-- ==========================================================

-- DATA ENGINEER
GRANT ROLE ROLE_RAW_DEV_READ TO ROLE ROLE_DATA_ENGINEER_DEV;
GRANT ROLE ROLE_RAW_DEV_WRITE TO ROLE ROLE_DATA_ENGINEER_DEV;
GRANT ROLE ROLE_TRANSFORMED_DEV_READ TO ROLE ROLE_DATA_ENGINEER_DEV;
GRANT ROLE ROLE_TRANSFORMED_DEV_WRITE TO ROLE ROLE_DATA_ENGINEER_DEV;

GRANT ROLE ROLE_RAW_PROD_READ TO ROLE ROLE_DATA_ENGINEER_PROD;
GRANT ROLE ROLE_TRANSFORMED_PROD_READ TO ROLE ROLE_DATA_ENGINEER_PROD;
-- keep prod write/create out unless explicitly required

-- DATA INGEST USER (interactive dev)
GRANT ROLE ROLE_RAW_DEV_READ TO ROLE ROLE_DATA_INGEST_DEV;
GRANT ROLE ROLE_RAW_DEV_WRITE TO ROLE ROLE_DATA_INGEST_DEV;
GRANT ROLE ROLE_RAW_DEV_CREATE TO ROLE ROLE_DATA_INGEST_DEV;
GRANT ROLE ROLE_SCHEMA_CREATE_RAW_DEV TO ROLE ROLE_DATA_INGEST_DEV;


-- DBT USER (interactive dev)
GRANT ROLE ROLE_RAW_DEV_READ TO ROLE ROLE_DBT_USER_DEV;
GRANT ROLE ROLE_TRANSFORMED_DEV_READ TO ROLE ROLE_DBT_USER_DEV;
GRANT ROLE ROLE_TRANSFORMED_DEV_WRITE TO ROLE ROLE_DBT_USER_DEV;
GRANT ROLE ROLE_TRANSFORMED_DEV_CREATE TO ROLE ROLE_DBT_USER_DEV;
GRANT ROLE ROLE_SCHEMA_CREATE_TRANSFORMED_DEV TO ROLE ROLE_DBT_USER_DEV;


-- DATA INGEST USER (PROD)
GRANT ROLE ROLE_RAW_PROD_READ TO ROLE ROLE_DATA_INGEST_PROD;
GRANT ROLE ROLE_RAW_PROD_WRITE TO ROLE ROLE_DATA_INGEST_PROD;
GRANT ROLE ROLE_RAW_PROD_CREATE TO ROLE ROLE_DATA_INGEST_PROD;
GRANT ROLE ROLE_SCHEMA_CREATE_RAW_PROD TO ROLE ROLE_DATA_INGEST_PROD;


-- Functional roles
GRANT ROLE ROLE_DATA_ENGINEER_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_DBT_USER_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_DATA_INGEST_DEV TO ROLE SYSADMIN;

GRANT ROLE ROLE_DATA_ENGINEER_PROD TO ROLE SYSADMIN;
GRANT ROLE ROLE_DBT_USER_PROD TO ROLE SYSADMIN;
GRANT ROLE ROLE_DATA_INGEST_PROD TO ROLE SYSADMIN;

-- Access roles
GRANT ROLE ROLE_RAW_DEV_READ TO ROLE SYSADMIN;
GRANT ROLE ROLE_RAW_DEV_WRITE TO ROLE SYSADMIN;
GRANT ROLE ROLE_RAW_DEV_CREATE TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_DEV_READ TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_DEV_WRITE TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_DEV_CREATE TO ROLE SYSADMIN;

GRANT ROLE ROLE_RAW_PROD_READ TO ROLE SYSADMIN;
GRANT ROLE ROLE_RAW_PROD_WRITE TO ROLE SYSADMIN;
GRANT ROLE ROLE_RAW_PROD_CREATE TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_PROD_READ TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_PROD_WRITE TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORMED_PROD_CREATE TO ROLE SYSADMIN;

-- Schema creation
GRANT ROLE ROLE_SCHEMA_CREATE_RAW_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_SCHEMA_CREATE_RAW_PROD TO ROLE SYSADMIN;
GRANT ROLE ROLE_SCHEMA_CREATE_TRANSFORMED_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_SCHEMA_CREATE_TRANSFORMED_PROD TO ROLE SYSADMIN;

-- Optional aggregation role
GRANT ROLE ROLE_DATA_ENGINEER_ALL_READ TO ROLE SYSADMIN;

-- Ownership roles (choose one policy)
-- Policy A (operational convenience): grant to SYSADMIN
GRANT ROLE ROLE_OWNER_RAW_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_OWNER_RAW_PROD TO ROLE SYSADMIN;
GRANT ROLE ROLE_OWNER_TRANSFORMED_DEV TO ROLE SYSADMIN;
GRANT ROLE ROLE_OWNER_TRANSFORMED_PROD TO ROLE SYSADMIN;
