GRANT USAGE ON DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;
GRANT SELECT ON ALL TABLES IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;
GRANT SELECT ON ALL VIEWS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_READ;

GRANT USAGE ON DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_WRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_WRITE;

GRANT USAGE ON DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE, CREATE STREAM, CREATE TASK, CREATE DCM PROJECT, CREATE DBT PROJECT
  ON ALL SCHEMAS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_CREATE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE, CREATE STREAM, CREATE TASK, CREATE DCM PROJECT, CREATE DBT PROJECT
  ON FUTURE SCHEMAS IN DATABASE TRANSFORMED_DEV TO ROLE ROLE_TRANSFORMED_DEV_CREATE;
