TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.SECURITY_INCIDENTS;

COPY INTO RAW_DEV.SQL_SERVER.SECURITY_INCIDENTS
FROM @RAW_DEV.SQL_SERVER.LANDING/security_incidents.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
