TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.USERS;

COPY INTO RAW_DEV.SQL_SERVER.USERS
FROM @RAW_DEV.SQL_SERVER.LANDING/users.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
