TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.LOGIN_LOGS;

COPY INTO RAW_DEV.SQL_SERVER.LOGIN_LOGS
FROM @RAW_DEV.SQL_SERVER.LANDING/login_logs.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
