TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.ORGANIZATIONS;

COPY INTO RAW_DEV.SQL_SERVER.ORGANIZATIONS
FROM @RAW_DEV.SQL_SERVER.LANDING/organizations.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
