TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.NETWORK_EVENTS;

COPY INTO RAW_DEV.SQL_SERVER.NETWORK_EVENTS
FROM @RAW_DEV.SQL_SERVER.LANDING/network_events.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
