TRUNCATE TABLE IF EXISTS RAW_DEV.SQL_SERVER.SYSTEMS;

COPY INTO RAW_DEV.SQL_SERVER.SYSTEMS
FROM @RAW_DEV.SQL_SERVER.LANDING/systems.csv
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT=(
    TYPE=CSV
    PARSE_HEADER = TRUE
);
